"""Cmdb/wireless-controller connectors."""

from fortigate_api.cmdb.wireless_controller.access_control_list import AccessControlListWcC
from fortigate_api.cmdb.wireless_controller.address import AddressWcC
from fortigate_api.cmdb.wireless_controller.addrgrp import AddrgrpWcC
from fortigate_api.cmdb.wireless_controller.ap_status import ApStatusWcC
from fortigate_api.cmdb.wireless_controller.apcfg_profile import ApcfgProfileWcC
from fortigate_api.cmdb.wireless_controller.arrp_profile import ArrpProfileWcC
from fortigate_api.cmdb.wireless_controller.ble_profile import BleProfileWcC
from fortigate_api.cmdb.wireless_controller.bonjour_profile import BonjourProfileWcC
from fortigate_api.cmdb.wireless_controller.global_ import GlobalWcC
from fortigate_api.cmdb.wireless_controller.inter_controller import InterControllerWcC
from fortigate_api.cmdb.wireless_controller.log import LogWcC
from fortigate_api.cmdb.wireless_controller.mpsk_profile import MpskProfileWcC
from fortigate_api.cmdb.wireless_controller.qos_profile import QosProfileWcC
from fortigate_api.cmdb.wireless_controller.region import RegionWcC
from fortigate_api.cmdb.wireless_controller.setting import SettingWcC
from fortigate_api.cmdb.wireless_controller.snmp import SnmpWcC
from fortigate_api.cmdb.wireless_controller.timers import TimersWcC
from fortigate_api.cmdb.wireless_controller.utm_profile import UtmProfileWcC
from fortigate_api.cmdb.wireless_controller.vap import VapWcC
from fortigate_api.cmdb.wireless_controller.vap_group import VapGroupWcC
from fortigate_api.cmdb.wireless_controller.wag_profile import WagProfileWcC
from fortigate_api.cmdb.wireless_controller.wids_profile import WidsProfileWcC
from fortigate_api.cmdb.wireless_controller.wireless_controller_c import WirelessControllerC
from fortigate_api.cmdb.wireless_controller.wtp import WtpWcC
from fortigate_api.cmdb.wireless_controller.wtp_group import WtpGroupWcC
from fortigate_api.cmdb.wireless_controller.wtp_profile import WtpProfileWcC
