"""Cmdb/switch-controller connectors."""

from fortigate_api.cmdb.switch_controller.global_ import GlobalScC
from fortigate_api.cmdb.switch_controller.lldp_profile import LldpProfileScC
from fortigate_api.cmdb.switch_controller.lldp_settings import LldpSettingsScC
from fortigate_api.cmdb.switch_controller.location import LocationScC
from fortigate_api.cmdb.switch_controller.mac_policy import MacPolicyScC
from fortigate_api.cmdb.switch_controller.managed_switch import ManagedSwitchScC
from fortigate_api.cmdb.switch_controller.nac_device import NacDeviceScC
from fortigate_api.cmdb.switch_controller.nac_settings import NacSettingsScC
from fortigate_api.cmdb.switch_controller.port_policy import PortPolicyScC
from fortigate_api.cmdb.switch_controller.snmp_community import SnmpCommunityScC
from fortigate_api.cmdb.switch_controller.stp_instance import StpInstanceScC
from fortigate_api.cmdb.switch_controller.stp_settings import StpSettingsScC
from fortigate_api.cmdb.switch_controller.switch_controller_c import SwitchControllerC
from fortigate_api.cmdb.switch_controller.switch_group import SwitchGroupScC
from fortigate_api.cmdb.switch_controller.system import SystemScC
from fortigate_api.cmdb.switch_controller.vlan_policy import VlanPolicyScC
